name: Deno

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.12.1
      - run: deno cache src/deps/*
      - run: deno test
      - run: deno cache src/main.ts
      - run: deno lint
      - run: deno fmt --check
